---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: spring-boot-example
  namespace: demo 
spec:
  pathname: https://github.com/otp-demo/otp-gitops-apps.git
  type: GitHub
