---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: spring-boot-example 
  name: spring-boot-example-placement-1
  namespace: demo 
spec:
  clusterSelector:
    matchLabels:
      app: springboot
