---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: demo-apps/springboot/manifests
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: spring-boot-example
  name: spring-boot-example-subscription-1
  namespace: demo
spec:
  channel: telstra-customer-a/spring-boot-example
  placement:
    placementRef:
      kind: PlacementRule
      name: spring-boot-example-placement-1
