apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
namespace: telstra-customer-a

#use the following to update the image
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: quay.io/nickmerrett/spring-boot-example:latest
    target:
      kind: Deployment
      name: spring-boot-example