apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: openshift-serverless-subscription
  namespace: openshift-serverless
  labels:
    app: openshift-serverless
  annotations:
      apps.open-cluster-management.io/git-branch: master
      apps.open-cluster-management.io/git-path: clusters/cluster-services/openshift-serverless/manifests/ 
      apps.open-cluster-management.io/reconcile-option: replace
spec:
  channel: openshift-serverless/openshift-serverless-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: openshift-serverless-placement-1
#      apiGroup: apps.open-cluster-management.io