---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: tpn
  name: tpn-placement-rule
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      'purpose': 'tpn'
