---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: clusters/tpn-operator/tpn
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: tpn
  name: tpn-subscription
  namespace: default
spec:
  channel: tpn-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: tpn-placement-rule
