---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: clusters/cockroachdb/aws/deploy-cockroachdb/deploy
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: cockroachdb-aws
  name: cockroachdb-subscription-aws
  namespace: multi-cluster-cockroachdb
spec:
  channel: multi-cluster-cockroachdb/cockroachdb-aws-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: cockroachdb-placement-aws
