---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: aws-credentials
  namespace: openshift-logging 
spec:
  refreshInterval: "10m"
  secretStoreRef:
    name: secretstore-vault
    kind: ClusterSecretStore
  target:
    name: aws-credentials
  data:
  - secretKey: aws_access_key_id 
    remoteRef:
      key: secrets/awscreds
      property: aws_access_key_id
  - secretKey: aws_secret_access_key
    remoteRef:
      key: secrets/awscreds
      property: aws_secret_access_key