apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: openshift-logging-
  annotations:
    olm.providedAPIs: >-
      ClusterLogForwarder.v1.logging.openshift.io,ClusterLogging.v1.logging.openshift.io
  namespace: openshift-logging
  name: openshift-logging
spec:
  targetNamespaces:
    - openshift-logging