resources:
  - namespace.yaml 
  - certificate.yaml # needs cert-manager
  - cluster-secret-store.yaml # needs cert-manager
  - cm-vault-config.yaml 
  - cr-allow-nonroot-scc.yaml
  - cr-statefulset-get-klusterlet.yaml
  - cr-vault-agent-injector.yaml
  - crb-statefulset-get-klusterlet.yaml
  - crb-vault-agent-injector.yaml
  - crb-vault-nonroot-scc.yaml
  - crb-vault-server-binding.yaml
  - crb-vault-system-auth.yaml
#  - credentials-request.yaml
  - deployment.yaml
  - issuer.yaml   #needs cert-manager
  - mutating-webhook-configuration.yaml
  - netpol-vault.yaml
  - pdb-vault.yaml
  - role-vault.yaml
  - rolebinding.yaml
  - route.yaml
  - sa-vault.yaml
  - service-vault-active.yaml
  - service-vault-agent-injector.yaml
  - service-vault-internal.yaml
  - service-vault-standby.yaml
  - service-vault-ui.yaml
  - service-vault.yaml
  - serviceexport.yaml # needs submariner
  - statefulset.yaml

patches:
  - target:
      kind: Route 
      name: vault-global
    patch: |-
      - op: replace 
        path: /spec/host
        value: vault.swinney.io
  - target:
      kind: Certificate 
      name: vault-route
    patch: |-
      - op: replace 
        path: /spec/dnsNames
        value: 
          - vault.apps.aws0.mutihybridcloudkitchen.com
          - vault.apps.aws1.mutihybridcloudkitchen.com
          - vault.apps.azure0.azure01.ibmdojo01.com
          - vault.swinney.io
  - target:
      kind: Certificate 
      name: vault-tls
    patch: |-
      - op: replace 
        path: /spec/dnsNames
        value: 
          - vault-0.aws0.vault-internal.vault.svc.clusterset.local
          - vault-1.aws0.vault-internal.vault.svc.clusterset.local
          - vault-2.aws0.vault-internal.vault.svc.clusterset.local
          - vault-0.aws1.vault-internal.vault.svc.clusterset.local
          - vault-1.aws1.vault-internal.vault.svc.clusterset.local
          - vault-2.aws1.vault-internal.vault.svc.clusterset.local
          - vault-0.azure0.vault-internal.vault.svc.clusterset.local
          - vault-1.azure0.vault-internal.vault.svc.clusterset.local
          - vault-2.azure0.vault-internal.vault.svc.clusterset.local
          - vault-0.vault-internal
          - vault-0.vault-internal.vault.svc
          - vault-0.vault-internal.vault.svc.cluster.local
          - vault-1.vault-internal
          - vault-1.vault-internal.vault.svc
          - vault-1.vault-internal.vault.svc.cluster.local
          - vault-2.vault-internal
          - vault-2.vault-internal.vault.svc
          - vault-2.vault-internal.vault.svc.cluster.local
          - vault
          - vault.vault.svc
          - vault.vault.svc.cluster.local
  - target:
      kind: Certificate 
      name: vault-tls
    patch: |-
      - op: replace 
        path: /spec/dnsNames
        value: 
          - vault-0.aws0.vault-internal.vault.svc.clusterset.local
          - vault-1.aws0.vault-internal.vault.svc.clusterset.local
          - vault-2.aws0.vault-internal.vault.svc.clusterset.local
          - vault-0.aws1.vault-internal.vault.svc.clusterset.local
          - vault-1.aws1.vault-internal.vault.svc.clusterset.local
          - vault-2.aws1.vault-internal.vault.svc.clusterset.local
          - vault-0.azure0.vault-internal.vault.svc.clusterset.local
          - vault-1.azure0.vault-internal.vault.svc.clusterset.local
          - vault-2.azure0.vault-internal.vault.svc.clusterset.local
          - vault-0.vault-internal
          - vault-0.vault-internal.vault.svc
          - vault-0.vault-internal.vault.svc.cluster.local
          - vault-1.vault-internal
          - vault-1.vault-internal.vault.svc
          - vault-1.vault-internal.vault.svc.cluster.local
          - vault-2.vault-internal
          - vault-2.vault-internal.vault.svc
          - vault-2.vault-internal.vault.svc.cluster.local
          - vault
          - vault.vault.svc
          - vault.vault.svc.cluster.local
  - target:
      kind: ConfigMap  
      name: vault-config
    patch: |-
      - op: replace 
        path: /data/extraconfig-from-values.hcl
        value: |-
          disable_mlock = true
          ui = true

          listener "tcp" {
            address = "[::]:8200"
            cluster_address = "[::]:8201"
            tls_cert_file="/etc/vault-tls/tls.crt"
            tls_key_file="/etc/vault-tls/tls.key"
            tls_client_ca_file="/etc/vault-tls/ca.crt"
          }

          storage "raft" {
            path = "/vault/data"

            retry_join {
              leader_api_addr = "https://vault-0.aws0.vault-internal.vault.svc.clusterset.local:8200"
              leader_ca_cert_file = "/etc/vault-tls/ca.crt"
            }

            retry_join {
              leader_api_addr = "https://vault-1.aws0.vault-internal.vault.svc.clusterset.local:8200"
              leader_ca_cert_file = "/etc/vault-tls/ca.crt"
            }

            retry_join {
              leader_api_addr = "https://vault-2.aws0.vault-internal.vault.svc.clusterset.local:8200"
              leader_ca_cert_file = "/etc/vault-tls/ca.crt"
            }

            retry_join {
              leader_api_addr = "https://vault-0.aws1.vault-internal.vault.svc.clusterset.local:8200"
              leader_ca_cert_file = "/etc/vault-tls/ca.crt"
            }

            retry_join {
              leader_api_addr = "https://vault-1.aws1.vault-internal.vault.svc.clusterset.local:8200"
              leader_ca_cert_file = "/etc/vault-tls/ca.crt"
            }

            retry_join {
              leader_api_addr = "https://vault-2.aws1.vault-internal.vault.svc.clusterset.local:8200"
              leader_ca_cert_file = "/etc/vault-tls/ca.crt"
            }

            retry_join {
              leader_api_addr = "https://vault-0.azure0.vault-internal.vault.svc.clusterset.local:8200"
              leader_ca_cert_file = "/etc/vault-tls/ca.crt"
            }

            retry_join {
              leader_api_addr = "https://vault-1.azure0.vault-internal.vault.svc.clusterset.local:8200"
              leader_ca_cert_file = "/etc/vault-tls/ca.crt"
            }

            retry_join {
              leader_api_addr = "https://vault-2.azure0.vault-internal.vault.svc.clusterset.local:8200"
              leader_ca_cert_file = "/etc/vault-tls/ca.crt"
            }

          }

          log_level = "debug"

          service_registration "kubernetes" {}