---
# Source: vault-multicluster/templates/route.yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: vault
  annotations:
    cert-utils-operator.redhat-cop.io/destinationCA-from-secret: vault-tls
    cert-utils-operator.redhat-cop.io/certs-from-secret: vault-route-tls
  spec:
    port:
    targetPort: https
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
  to:
    kind: Service
    name: vault-ui
---
# Source: vault-multicluster/templates/route.yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: vault-global
  annotations:
    cert-utils-operator.redhat-cop.io/destinationCA-from-secret: vault-tls
    cert-utils-operator.redhat-cop.io/certs-from-secret: vault-route-tls
spec:
  host: vault.swinney.io
  port:
    targetPort: https
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
  to:
    kind: Service
    name: vault-ui