---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: clusters/cockroachdb/cockroachdb-deploy/deploy
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: cockroachdb
  name: cockroachdb-subscription
  namespace: multi-cluster-cockroachdb
spec:
  channel: multi-cluster-cockroachdb/cockroachdb-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: cockroachdb-placement
