apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:scc:anyuid
  namespace: {{ .Values.namespace }}
  annotations:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.namespace }}
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: hpa
#   namespace: {{ .Values.namespace }}-demo
# rules:
#   - apiGroups:
#       - autoscaling
#     resources:
#       - horizontalpodautoscalers
#     verbs:
#       - "*"
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: hpa
#   namespace: {{ .Values.namespace }}-demo
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: Role
#   name: hpa
# subjects:
#   - kind: ServiceAccount
#     name: openshift-gitops-cntk-argocd-application-controller
#     namespace: openshift-gitops