---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: aws-credentials
  namespace: amazon-cloudwatch
spec:
  refreshInterval: "10m"
  secretStoreRef:
    name: secretstore-vault
    kind: ClusterSecretStore
  target:
    name: awscreds
  data:
  - secretKey: credentials 
    remoteRef:
      key: secrets/awscreds
      property: cwagent 