{{- range .Values.cdbClusters }}
apiVersion: batch/v1
kind: Job
metadata:
  name: cockroachdb-post-deploy-{{ . }}
  namespace: openshift-gitops
spec:
  template:
    spec:
      containers:
      - name: cockroachdb-post-deploy-{{ . }}
        image: quay.io/marwan_attar_ibm/cockroachdb_initialisation:latest
        imagePullPolicy: Always
        env:
          - name: CLUSTER_LIST
            value: {{ . }}
          - name: IDENTIFIER
            value: ABCDEF
          - name: NAMESPACE
            value: multi-cluster-cockroachdb
          - name: STATEFULSET
            value: cockroachdb
          - name: ORGANISATION
            value: "Red Hat"
          - name: LICENSE
            value: "crl-0-ELnh2JEGGAIiB1JlZCBIYXQ"
      restartPolicy: OnFailure
  backoffLimit: 2
---
{{- end }}