{{- range .Values.cdbClusters }}
apiVersion: batch/v1
kind: Job
metadata:
  name: cockroachdb-post-deploy-{{ . }}
  namespace: openshift-gitops
spec:
  template:
    spec:
      containers:
      - name: cockroachdb-post-deploy-{{ . }}
        image: quay.io/langley_millard_ibm/patch_cockroach:latest 
        imagePullPolicy: Always
        env:
          - name: CLUSTER_LIST
            value: {{ . }}
          - name: IDENTIFIER
            value: ABCDEF   # FIXME
          - name: NAMESPACE
            value: multi-cluster-cockroachdb
          - name: STATEFULSET
            value: cockroachdb  
      restartPolicy: OnFailure
  backoffLimit: 2
---
{{- end }}