---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: demo-web-b
  name: demo-web-b
  namespace: telstra-customer-b
spec:
  clusterSelector:
    matchLabels:
      'demo': 'telstra'
