---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: demo-web/web-b/web-b
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: demo-web-b
  name: web-b-subscription-1
  namespace: telstra-customer-b
spec:
  channel: telstra-customer-b/web-b-latest
  placement:
    placementRef:
      kind: PlacementRule
      name: demo-web-b
