---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: demo-web-a
  namespace: telstra-customer-a-demo
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - demo-web-a
