---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: demo-web-a
  name: demo-web-a
  namespace: telstra-customer-a-demo
spec:
  clusterSelector:
    matchLabels:
      'demo-v1': 'telstra'
