apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:scc:anyuid
  namespace: telstra-customer-a-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: default
  namespace: telstra-customer-a-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hpa
  namespace: telstra-customer-a-demo
rules:
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hpa
  namespace: telstra-customer-a-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hpa
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-cntk-argocd-application-controller
    namespace: openshift-gitops

