---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: demo-web/web-a/web-a
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: demo-web-a
  name: web-a-subscription-1
  namespace: telstra-customer-a-demo
spec:
  channel: telstra-customer-a-demo/web-a-latest
  placement:
    placementRef:
      kind: PlacementRule
      name: demo-web-a
