apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: cert-utils-placement-1
  namespace: cert-utils 
  labels:
    app: cert-utils
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions: []
    matchLabels:
      # Replace value with Cluster you wish to provision too.
      cluster.open-cluster-management.io/clusterset: multicloud-cluster-set
