apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: cert-utils-subscription
  namespace: cert-utils 
  labels:
    app: cert-utils
  annotations:
      apps.open-cluster-management.io/git-branch: master 
      apps.open-cluster-management.io/git-path: clusters/cluster-services/cert-utils/manifests/ 
      apps.open-cluster-management.io/reconcile-option: replace
spec:
  channel: cert-utils/cert-utils-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: cert-utils-placement-1
#      apiGroup: apps.open-cluster-management.io