apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: knative-serving-subscription
  namespace: knative-serving
  labels:
    app: knative-serving
  annotations:
      apps.open-cluster-management.io/git-branch: master
      apps.open-cluster-management.io/git-path: clusters/cluster-services/knative-serving/manifests/ 
      apps.open-cluster-management.io/reconcile-option: replace
spec:
  channel: knative-serving/knative-serving-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: knative-serving-placement-1
#      apiGroup: apps.open-cluster-management.io