apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: openshift-logging-placement-1
  namespace: openshift-logging 
  labels:
    app: openshift-logging
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions: []
    matchLabels:
      # Replace value with Cluster you wish to provision too.
      cluster.open-cluster-management.io/clusterset: multicloud-cluster-set