apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: openshift-logging-subscription
  namespace: openshift-logging 
  labels:
    app: openshift-logging
    app.kubernetes.io/instance: apps-cluster-services-openshift-logging
  annotations:
      apps.open-cluster-management.io/git-branch: master 
      apps.open-cluster-management.io/git-path: clusters/cluster-services/openshift-logging/manifests/ 
      apps.open-cluster-management.io/reconcile-option: replace
spec:
  channel: openshift-logging/openshift-logging-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: openshift-logging-placement-1
#      apiGroup: apps.open-cluster-management.io